// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: firebase_event.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct FirebasePayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var data: [FirebaseBatch] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FirebaseBatch: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var events: [FirebaseEvent] = []

  var userAttributes: [FirebaseUserAttribute] = []

  /// https://github.com/lari/firebase-ga4-app-measurement-protobuf
  var platform: String = String()

  var osVersion: String = String()

  var deviceModel: String = String()

  var userDefaultLanguage: String = String()

  var appInstallMethod: String = String()

  var appID: String = String()

  var appVersion: String = String()

  var appInstanceID: String = String()

  var gmpAppID: String = String()

  var deviceID: String = String()

  var firebaseInstanceID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FirebaseEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var eventProperties: [FirebaseProperty] = []

  var eventName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FirebaseProperty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: String = String()

  var strValue: String = String()

  var numValue: UInt64 = 0

  var itemsValue: [ListItem] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct FirebaseUserAttribute: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var key: String = String()

  var strValue: String = String()

  var numValue: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct ListItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fields: [FirebaseProperty] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension FirebasePayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FirebasePayload"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.data, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FirebasePayload, rhs: FirebasePayload) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FirebaseBatch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FirebaseBatch"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}events\0\u{3}user_attributes\0\u{2}\u{5}platform\0\u{3}os_version\0\u{3}device_model\0\u{3}user_default_language\0\u{4}\u{2}app_install_method\0\u{3}app_id\0\u{4}\u{2}app_version\0\u{4}\u{5}app_instance_id\0\u{4}\u{4}gmp_app_id\0\u{4}\u{2}device_id\0\u{4}\u{3}firebase_instance_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.events) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.userAttributes) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.osVersion) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.deviceModel) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.userDefaultLanguage) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.appInstallMethod) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self.appID) }()
      case 16: try { try decoder.decodeSingularStringField(value: &self.appVersion) }()
      case 21: try { try decoder.decodeSingularStringField(value: &self.appInstanceID) }()
      case 25: try { try decoder.decodeSingularStringField(value: &self.gmpAppID) }()
      case 27: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 30: try { try decoder.decodeSingularStringField(value: &self.firebaseInstanceID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.events.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.events, fieldNumber: 2)
    }
    if !self.userAttributes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.userAttributes, fieldNumber: 3)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 8)
    }
    if !self.osVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.osVersion, fieldNumber: 9)
    }
    if !self.deviceModel.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceModel, fieldNumber: 10)
    }
    if !self.userDefaultLanguage.isEmpty {
      try visitor.visitSingularStringField(value: self.userDefaultLanguage, fieldNumber: 11)
    }
    if !self.appInstallMethod.isEmpty {
      try visitor.visitSingularStringField(value: self.appInstallMethod, fieldNumber: 13)
    }
    if !self.appID.isEmpty {
      try visitor.visitSingularStringField(value: self.appID, fieldNumber: 14)
    }
    if !self.appVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.appVersion, fieldNumber: 16)
    }
    if !self.appInstanceID.isEmpty {
      try visitor.visitSingularStringField(value: self.appInstanceID, fieldNumber: 21)
    }
    if !self.gmpAppID.isEmpty {
      try visitor.visitSingularStringField(value: self.gmpAppID, fieldNumber: 25)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 27)
    }
    if !self.firebaseInstanceID.isEmpty {
      try visitor.visitSingularStringField(value: self.firebaseInstanceID, fieldNumber: 30)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FirebaseBatch, rhs: FirebaseBatch) -> Bool {
    if lhs.events != rhs.events {return false}
    if lhs.userAttributes != rhs.userAttributes {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.osVersion != rhs.osVersion {return false}
    if lhs.deviceModel != rhs.deviceModel {return false}
    if lhs.userDefaultLanguage != rhs.userDefaultLanguage {return false}
    if lhs.appInstallMethod != rhs.appInstallMethod {return false}
    if lhs.appID != rhs.appID {return false}
    if lhs.appVersion != rhs.appVersion {return false}
    if lhs.appInstanceID != rhs.appInstanceID {return false}
    if lhs.gmpAppID != rhs.gmpAppID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.firebaseInstanceID != rhs.firebaseInstanceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FirebaseEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FirebaseEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}event_properties\0\u{3}event_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.eventProperties) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.eventName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.eventProperties.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.eventProperties, fieldNumber: 1)
    }
    if !self.eventName.isEmpty {
      try visitor.visitSingularStringField(value: self.eventName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FirebaseEvent, rhs: FirebaseEvent) -> Bool {
    if lhs.eventProperties != rhs.eventProperties {return false}
    if lhs.eventName != rhs.eventName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FirebaseProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FirebaseProperty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}str_value\0\u{3}num_value\0\u{4}\u{3}items_value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.strValue) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.numValue) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.itemsValue) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.strValue.isEmpty {
      try visitor.visitSingularStringField(value: self.strValue, fieldNumber: 2)
    }
    if self.numValue != 0 {
      try visitor.visitSingularUInt64Field(value: self.numValue, fieldNumber: 3)
    }
    if !self.itemsValue.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.itemsValue, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FirebaseProperty, rhs: FirebaseProperty) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.strValue != rhs.strValue {return false}
    if lhs.numValue != rhs.numValue {return false}
    if lhs.itemsValue != rhs.itemsValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FirebaseUserAttribute: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "FirebaseUserAttribute"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}key\0\u{3}str_value\0\u{3}num_value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.strValue) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.numValue) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 2)
    }
    if !self.strValue.isEmpty {
      try visitor.visitSingularStringField(value: self.strValue, fieldNumber: 3)
    }
    if self.numValue != 0 {
      try visitor.visitSingularUInt64Field(value: self.numValue, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FirebaseUserAttribute, rhs: FirebaseUserAttribute) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.strValue != rhs.strValue {return false}
    if lhs.numValue != rhs.numValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ListItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "ListItem"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{6}fields\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.fields) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fields.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fields, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ListItem, rhs: ListItem) -> Bool {
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
